2017-05-10 10:07:37 Exception: 由于目标计算机积极拒绝，无法连接。
 in D:\www\workerman_web_age\_lib\GlobalData\Client.php:72
Stack trace:
#0 D:\www\workerman_web_age\_lib\GlobalData\Client.php(139): GlobalData\Client->getConnection('id_cache_sessio...')
#1 D:\www\workerman_web_age\_lib\GlobalData\Client.php(114): GlobalData\Client->__get('id_cache_sessio...')
#2 D:\www\workerman_web_age\_lib\lib\base\DBBase.php(138): GlobalData\Client->__isset('id_cache_sessio...')
#3 D:\www\workerman_web_age\_lib\Workerman_win\Protocols\Http.php(433): lib\base\DBBase::find('1494381462_3g31...')
#4 D:\www\workerman_web_age\_lib\Workerman_win\Protocols\Http.php(306): Workerman\Protocols\Http::sessionStart_db()
#5 D:\www\workerman_web_age\_lib\lib\helper.php(72): Workerman\Protocols\Http::sessionStart()
#6 D:\www\workerman_web_age\z_admin\controller\IndexController.php(17): session('admin')
#7 [internal function]: z_admin\controller\IndexController::login(Object(ape\App), Array)
#8 D:\www\workerman_web_age\_lib\ape\App.php(182): call_user_func('z_admin\\control...', Object(ape\App), Array)
#9 [internal function]: ape\App->onMessage(Object(Workerman\Connection\TcpConnection), Array)
#10 D:\www\workerman_web_age\_lib\Workerman_win\Connection\TcpConnection.php(480): call_user_func(Array, Object(Workerman\Connection\TcpConnection), Array)
#11 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #106)
#12 D:\www\workerman_web_age\_lib\Workerman_win\Events\Select.php(257): call_user_func_array(Array, Array)
#13 D:\www\workerman_web_age\_lib\Workerman_win\Worker.php(808): Workerman\Events\Select->loop()
#14 D:\www\workerman_web_age\_lib\ape\App.php(244): Workerman\Worker->run()
#15 D:\www\workerman_web_age\_lib\Workerman_win\Worker.php(457): ape\App->run()
#16 D:\www\workerman_web_age\_lib\Workerman_win\Worker.php(366): Workerman\Worker::runAllWorkers()
#17 D:\www\workerman_web_age\start.php(35): Workerman\Worker::runAll()
#18 {main}
